pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'echo "build"'
      }
    }
    stage('Test') {
      steps {
        sh 'echo "test"'
      }
    }
  }
}
